### ISSUE TITLE
Missing .gitignore

### ISSUE THREAD

**Issue by lee-leonardo** [jmcateer/grunt-qunit-missed#1]
Hey Jeremy, this is Leo. I should probably get a account with my expedia email to do this... but whatever.
It's good to add a .gitignore file [here's a link](https://github.com/github/gitignore/blob/master/Node.gitignore)
You can add it via the admin tools in github.
After that if you `git checkout -- <insertFileNameHere>` you will be able to remove files and folders you do not want exposed to git (meaning the node_modules and the grunt_modules folders and such). It'll make the git commits a lot easier to look at (and only code you are responsible for!).

**Comment by jmcateer** [comment]
Thanks for the tip.
Added before I read this.  Was very ugly with so many files.

Jer

Sent from my Windows Phone

-----Original Message-----
